package fr.dok.chabadabada.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHABADA_CARD.
 */
public class ChabadaCard {

    private Long id;
    private String FRENCH_WORD;
    private String ENGLISH_WORD;
    private Integer CARD_TYPE;

    public ChabadaCard() {
    }

    public ChabadaCard(Long id) {
        this.id = id;
    }

    public ChabadaCard(Long id, String FRENCH_WORD, String ENGLISH_WORD, Integer CARD_TYPE) {
        this.id = id;
        this.FRENCH_WORD = FRENCH_WORD;
        this.ENGLISH_WORD = ENGLISH_WORD;
        this.CARD_TYPE = CARD_TYPE;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFRENCH_WORD() {
        return FRENCH_WORD;
    }

    public void setFRENCH_WORD(String FRENCH_WORD) {
        this.FRENCH_WORD = FRENCH_WORD;
    }

    public String getENGLISH_WORD() {
        return ENGLISH_WORD;
    }

    public void setENGLISH_WORD(String ENGLISH_WORD) {
        this.ENGLISH_WORD = ENGLISH_WORD;
    }

    public Integer getCARD_TYPE() {
        return CARD_TYPE;
    }

    public void setCARD_TYPE(Integer CARD_TYPE) {
        this.CARD_TYPE = CARD_TYPE;
    }

}
