package fr.dok.chabadabada.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import fr.dok.chabadabada.model.ChabadaCard;

import fr.dok.chabadabada.model.ChabadaCardDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chabadaCardDaoConfig;

    private final ChabadaCardDao chabadaCardDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chabadaCardDaoConfig = daoConfigMap.get(ChabadaCardDao.class).clone();
        chabadaCardDaoConfig.initIdentityScope(type);

        chabadaCardDao = new ChabadaCardDao(chabadaCardDaoConfig, this);

        registerDao(ChabadaCard.class, chabadaCardDao);
    }
    
    public void clear() {
        chabadaCardDaoConfig.getIdentityScope().clear();
    }

    public ChabadaCardDao getChabadaCardDao() {
        return chabadaCardDao;
    }

}
